### ISSUE TITLE
Windows signing cert expired (Protocol Labs, Inc)

### ISSUE THREAD

**Issue by lidel** [ipfs/distributions#639]
```
 Issued to: Protocol Labs, Inc.
 Issued by: DigiCert SHA2 Assured ID Code Signing CA
 Expires: Wed Feb 16 12:00:00 2022
 SHA1 hash: FC029D1A7E8F3AB127B883DE792A940BD7A2CE7D
```

Impact: P0. 
This is used for dist.ipfs.io, ipfs-desktop and filecoin-station, and we are unable to make a release without signing.

## Timeline

- Today: (still waiting for digiCert)
- 2022-02-21: submitted official renewal request (after fighting with DigiCert interface and account policies for days)
- 2022-02-16: old cert expired

## Tasks

- [x] understand  how old cert was created
- [x] disable windows signing
- [x] understand how bad UX looks on Windows (its [bad](https://github.com/ipfs/ipfs-desktop/issues/1983#issuecomment-1055964002))
- [x] get new cert (:hourglass_flowing_sand:  in progress)
  - [x] track down digicert renewal DRI / access / credentials
  - [x] DONE: filled request for a new cert  (21 Feb 2022)
  - [x] DONE: facepalm how long this takes  (23 Feb 2022)
  - [x] receive cert from digicert
  - [x] test new cert in ipfs-desktop repo
  - [x] update cert in our secure  shared GUI vault 
- [x] update in ipfs/distributions or continue in https://github.com/ipfs/distributions/issues/384
- [x] update in ipfs/ipfs-desktop
- [x] update in filecoin-project/filecoin-station
- [x] create process / reminder to ensure this never happens again

**Comment by lidel** [comment]
- We are still waiting  for DigiCert to provide us with renewed code signing cert.
- The cert cost in 2019 was 213 USD for 3 years. 
  - In 2022 renewal for another 3 years is 1422 USD  (tough times, the cost of recycled electrons went up)

**Comment by BigLep** [comment]
2022-03-01: @lidel  is going to followup givenn we haven't gont a renewed cert yet.

**Comment by lidel** [comment]
- The cert is renewed: IPFS Desktop and other GUI projects now build in a way that signs binaries for Windows.
- In regard to CLIs at dist.ipfs.io, this is not a priority, and we will track it in https://github.com/ipfs/distributions/issues/384
- I've enabled all expiration notifications at DigiCert + added internal notification 4 weeks before it expires, to minimize risk of us missing this again.
